version: "3.10"

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  celery:
    build: .
    volumes:
      - .:/src
    container_name: cl01
    command: celery -A server worker -l info
    links:
      - redis