# Generated by Django 4.1.3 on 2022-11-25 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_account_user_alter_account_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
    ]
