# Generated by Django 4.1.3 on 2022-11-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_account_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.BooleanField(default=False),
        ),
    ]
