# Generated by Django 4.1.3 on 2022-11-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_organization'),
        ('categories', '0002_alter_category_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
