# Generated by Django 4.1.3 on 2022-11-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_account_unique_together'),
        ('categories', '0003_delete_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'BasicCategory',
                'verbose_name_plural': 'BasicCategories',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_of_category',
        ),
        migrations.AddField(
            model_name='category',
            name='name_of_category',
            field=models.ManyToManyField(to='user.user'),
        ),
    ]
