# Generated by Django 4.1.3 on 2022-11-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_basiccategory_remove_category_name_of_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_of_category',
        ),
        migrations.AddField(
            model_name='category',
            name='name_of_category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
