# Generated by Django 4.1.3 on 2022-11-28 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_created'),
        ('categories', '0005_remove_category_name_of_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basiccategory',
            name='category',
        ),
        migrations.AddField(
            model_name='basiccategory',
            name='categories',
            field=models.ManyToManyField(to='categories.category'),
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
