# Generated by Django 4.1.3 on 2022-11-28 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_created'),
        ('categories', '0006_remove_basiccategory_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercategory',
            options={'verbose_name': 'UserCategory', 'verbose_name_plural': 'UserCategories'},
        ),
        migrations.AlterField(
            model_name='usercategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='user.user'),
        ),
    ]
